---
Name: user-denied-form
---
SilverStripe\UserForms\Form\UserForm:
  extensions:
    udf-security: DNADesign\UserDeniedForm\Extensions\UserFormSecurityExtension
SilverStripe\UserForms\Model\UserDefinedForm:
  extensions:
    udf-security: DNADesign\UserDeniedForm\Extensions\UserDefinedFormSecurityExtension
SilverStripe\UserForms\Model\Submission\SubmittedForm:
  extensions:
    udf-security: DNADesign\UserDeniedForm\Extensions\SubmittedFormSecurityExtension
SilverStripe\UserForms\Control\UserDefinedFormController:
  extensions:
    udf-security: DNADesign\UserDeniedForm\Extensions\UserDefinedFormControllerSecurityExtension
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    udf-security: DNADesign\UserDeniedForm\Extensions\SiteConfigUserDeniedFormExtension